# Default values - feel free to change 
initial_snapshot_depth = 1000
initial_starting_capacity = 1000
max_reconnect_attempts = 10
initial_backoff_ms = 100
max_backoff_ms = 30000
imbalance_depth_levels = 10

# Percentage of total trade volume that a single trade takes up to be considered significant
significant_trade_volume_pct = 0.05
significant_trades_display_count = 20

# Time since a trade was made until it's removed from the list
significant_trades_retention_secs = 120
